import {
    RiHomeFill,
    RiHomeLine,
    RiSearchLine,
    RiSearchFill,
    RiFilmLine,
    RiFilmFill,
    RiChat3Fill,
    RiChat3Line,
    RiHeartLine,
    RiHeartFill,
    RiAddBoxFill,
    RiAddBoxLine,
  } from "react-icons/ri";
  
export const routes = [
    {
      id: 0,
      icon: <RiHomeLine />,
      activeIcon: <RiHomeFill />,
      label: "Home",
      route: "/",
      showSmallScreen: true,
    },
    {
      id: 1,
      icon: <RiSearchLine />,
      activeIcon: <RiSearchFill />,
      label: "Busca",
      route: "/search",
      showSmallScreen: false,
    },
    {
      id: 2,
      icon: <RiFilmLine />,
      activeIcon: <RiFilmFill />,
      label: "Reels",
      route: "/reels",
      showSmallScreen: true,
    },
    {
      id: 3,
      icon: <RiHeartLine />,
      activeIcon: <RiHeartFill />,
      label: "Likes",
      route: "/likes",
      showSmallScreen: false,
    },
    {
      id: 4,
      icon: <RiChat3Line />,
      activeIcon: <RiChat3Fill />,
      label: "Messages",
      route: "/messages",
      showSmallScreen: true,
    },
    {
      id: 5,
      icon: <RiAddBoxLine />,
      activeIcon: <RiAddBoxFill />,
      label: "Create",
      route: undefined,
      showSmallScreen: true,
    },
  ];